//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace курсовая
{
    using System;
    using System.Collections.Generic;
    
    public partial class Account
    {
        public int id_account { get; set; }
        public string login_ { get; set; }
        public string password_ { get; set; }
        public Nullable<int> id_role { get; set; }
    
        public virtual C_Role C_Role { get; set; }
    }
}
