//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace курсовая
{
    using System;
    using System.Collections.Generic;
    
    public partial class Review
    {
        public int id_review { get; set; }
        public Nullable<int> id_source { get; set; }
        public Nullable<int> id_account { get; set; }
        public string review_text { get; set; }
        public Nullable<int> rating { get; set; }
        public Nullable<System.DateTime> review_date { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual Source_ Source_ { get; set; }
    }
}
