//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace курсовая
{
    using System;
    using System.Collections.Generic;
    
    public partial class SourceEditHistory
    {
        public int id_history { get; set; }
        public Nullable<int> id_source { get; set; }
        public Nullable<int> id_account { get; set; }
        public Nullable<System.DateTime> edit_date { get; set; }
        public string edit_description { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual Source_ Source_ { get; set; }
    }
}
