//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace курсовая
{
    using System;
    using System.Collections.Generic;
    
    public partial class User_
    {
        public int id_user { get; set; }
        public string first_name { get; set; }
        public string last_name { get; set; }
        public Nullable<int> id_account { get; set; }
    
        public virtual Account Account { get; set; }
    }
}
